apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratelimit.fullname" . }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 8081
      protocol: TCP
  selector:
    {{- include "ratelimit.selectorLabels" . | nindent 4 }}
