apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # kubernetes.io/tls-acme - is legacy kube-lego annotation.
    cert-manager.io/cluster-issuer: letsencrypt-prod
    #    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
#    nginx.ingress.kubernetes.io/enable-cors: "true"
#    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
#    nginx.ingress.kubernetes.io/cors-allow-origin: "https://<%= @vars['gateway']['host'] %>"
  name: envoy
spec:
  rules:
  - host: cs.ysv.pp.ua
    http:
      paths:
      - backend:
          serviceName: envoy
          servicePort: 10000
        path: /
  - host: rl.test.coinselect.com
    http:
      paths:
      - backend:
          serviceName: envoy
          servicePort: 10000
        path: /
  tls:
  - hosts:
    - cs.ysv.pp.ua
    secretName: cs-ysv-pp-ua
  - hosts:
    - rl.test.coinselect.com
    secretName: rl-test-coinselect-com
